TITLE_FONT_SIZE = 32

TITLE_HEIGHT = 40

BUTTON_WIDTH = 280

BUTTON_HEIGHT = 50

BUTTON_FONT_SIZE = 20

BUTTON_MARGIN = 30

BUTTON_BACKGROUND_COLOR = "#06AB98"

RELACAO_IMAGENS_TEXTOS = {
"identificacao_nome" : ["qual é seu nome?"],
"identificacao_idade" : ["qual é sua idade?"],
"identificacao_naturalidade" : ["de onde você é?"],
"identificacao_estado_civil" : ["qual é seu estado civil?"],
"identificacao_profissao" : ["você trabalha com o que?"],
"queixa_principal_pergunta_aberta" : ["como posso ajudar?"],
"queixa_principal_imagens_auxiliares" : ["imagens auxiliares"],
"HMA_inicio" : ["quando começou?"],
"HMA_local" : ["onde está o problema?"],
"HMA_evolucao" : ["ele se manteve igual, melhorou ou piorou?"],
"HMA_irradiacao" : ["ele se espalhou para algum lugar?"],
"HMA_sintomas" : ["sente mais alguma coisa?"],
"HMA_desencadeante" : ["o que você acha que causou o problema?"],
"HMA_agravante" : ["o que piora o problema?"],
"HMA_atenuante" : ["o que melhora o problema?"],
"HMA_medicamentos_nao_cronicos" : ["você tomou alguma medicação para o seu problema?"],
"HMA_medicamentos_nao_cronicos_dose" : ["qual a dose do medicamento?"],
"HMA_medicamentos_nao_cronicos_posologia" : ["tomou quantas vezes ao dia?"],
"HMA_decalogo_dor_local" : ["onde dói?"],
"HMA_decalogo_dor_irradiacao" : ["a dor se espalha para algum lugar?"],
"HMA_decalogo_dor_qualidade" : ["como é a dor?"],
"HMA_decalogo_dor_intensidade" : ["de 0 a 10, qual o nível da sua dor?"],
"HMA_decalogo_dor_duracao" : ["há quanto tempo dói?"],
"HMA_decalogo_dor_evolucao" : ["com o tempo, a dor piorou, melhorou ou ficou igual?"],
"HMA_decalogo_dor_funcoes_organicas" : ["a dor atrapalhou suas atividades?"],
"HMA_decalogo_dor_fatores_desencadeantes" : ["o que você acha que desencadeou a dor?"],
"HMA_decalogo_dor_fatores_atenuantes" : ["o que melhora a dor?"],
"HMA_decalogo_dor_fatores_agravantes" : ["o que piora a dor?"],
"HMA_decalogo_dor_sintomas_associados" : ["sente mais alguma coisa?"],
"HPP_cirurgias" : ["você já fez alguma cirurgia?"],
"HPP_cirurgias_quantidade" : ["quantas cirurgias você fez?"],
"HPP_alergias" : ["você tem alguma alergia?"],
"HPP_DCNT" : ["você tem alguma doença crônica?"],
"HPP_medicamentos_cronicos_tipo" : ["você toma algum remédio todo dia?"],
"HPP_medicamentos_cronicos_dose" : ["qual a dose do medicamento?"],
"HPP_medicamentos_cronicos_posologia" : ["quantas vezes ao dia você toma o medicamento?"],
"HPP_vacinacao" : ["você está com a vacinação em dia?"],
"Hfisio_DUM" : ["qual a data da sua última menstruação?"],
"Hfisio_gestacoes_quantidade" : ["quantas vezes você engravidou?"],
"Hfisio_gestacoes_partos" : ["seu parto foi normal/natural ou cesária?"],
"Hfisio_gestacoes_abortos" : ["você já teve algum aborto?"],
"Hfisio_relacao_sexual_sim_nao" : ["você tem relações sexuais?"],
"Hfisio_relacao_sexual_frequencia" : ["com que frequência você tem relações sexuais?"],
"Hfisio_relacao_sexual_parceiros" : ["você tem quantos parceiros sexuais?"],
"Hfisio_relacao_sexual_contraceptivos" : ["você usa algum método contraceptivo?"],
"Hfisio_exames_preventivos_mamografia" : ["quando foi sua última mamografia?"],
"Hfisio_exames_preventivos_citopatologico" : ["quando foi seu último papanicolau?"],
"Hfisio_menopausa_inicio" : ["você já parou de menstruar?"],
"Hfisio_menopausa_sintomas" : ["você está tendo algum sintoma parecido?"],
"Hfisio_puberdade_menarca" : ["quando você menstruou pela primeira vez?"],
"Hfisio_puberdade_telarca" : ["qual das imagens mais se parece com seus seios?"],
"Hfisio_puberdade_pubarca" : ["qual das imagens mais se parece com seus pelos pubianos?"],
"Hfisio_puberdade_sexarca" : ["quando você começou a ter relações sexuais?"],
"Hfamilial_trabalho" : ["alguém do seu trabalho está doente?"],
"Hfamilial_escola" : ["alguém da sua escola está doente?"],
"Hfamiliar_DCNT" : ["sua família tem alguma doença crônica?"],
"Hfamiliar_obitos" : ["algum familiar próximo seu já morreu?"],
"Hpsico_renda" : ["qual a sua renda familiar?"],
"Hpsico_habitacao_local" : ["você mora na cidade ou na fazenda?"],
"Hpsico_habitacao_saneamento" : ["na sua casa tem água encanada?"],
"Hpsico_habitacao_condicoes" : ["como é a sua casa?"],
"Hpsico_religiao" : ["você tem alguma religião?"],
"Hpsico_escolaridade" : ["você estudou até qual série?"],
"Hpsico_relacoes" : ["como são suas relações familiares?"],
"subst_alcool_uso" : ["você bebe?"],
"subst_alcool_inicio" : ["quando começou a beber?"],
"subst_alcool_quantidade" : ["quanto você bebe?"],
"subst_tabaco_uso" : ["você fuma?"],
"subst_tabaco_inicio" : ["quando começou a fumar?"],
"subst_tabaco_quantidade" : ["quantos cigarros você fuma por dia?"],
"subst_drogas_ilicitas_uso" : ["você usa outras drogas?"],
"subst_drogas_ilicitas_inicio" : ["quando começou a usar drogas?"],
"subst_drogas_ilicitas_quantidade" : ["quanto você usa?"],
"habitos_alimentacao" : ["como é sua alimentação?"],
"habitos_higiene" : ["como é sua higiene?"],
"habitos_atividade_fisica" : ["você pratica alguma atividade física?"],
"habitos_sono" : ["como é seu sono?"],
"revisao_sistemas_cardiovascular" : ["você tem/teve algum sintoma parecido?"],
"revisao_sistemas_respiratorio" : ["você tem/teve algum sintoma parecido?"],
"revisao_sistemas_TGI" : ["você tem/teve algum sintoma parecido?"],
"revisao_sistemas_urogenital" : ["você tem/teve algum sintoma parecido?"],
"revisao_sistemas_endocrino" : ["você tem/teve algum sintoma parecido?"],
"revisao_sistemas_neurologico" : ["você tem/teve algum sintoma parecido?"],
"revisao_sistemas_osteomuscular" : ["você tem/teve algum sintoma parecido?"],
"revisao_sistemas_hematologico" : ["você tem/teve algum sintoma parecido?"],
}