RELACAO_IMAGENS_TEXTOS = {
"identificacao_nome" : ["qual o seu nome?"],
"identificacao_idade" : ["qual a sua idade?"],
"identificacao_naturalidade" : ["de onde você é?"],
"identificacao_estado_civil" : ["qual o seu estado civil?"],
"identificacao_profissao" : ["trabalha com o que?"],
"queixa_principal" : ["como posso ajudar?"],
"HMA_inicio" : ["quando começou?"],
"HMA_local" : ["onde está o problema?"],
"HMA_evolucao" : ["ele se manteve igual, melhorou ou piorou?"],
"HMA_irradiacao" : ["ele se espalhou para algum lugar?"],
"HMA_sintomas" : ["sente mais alguma coisa?"],
"HMA_desencadeantes" : ["o que você acha que desencadeou o problema?"],
"HMA_agravantes" : ["o que piora o problema?"],
"HMA_atenuantes" : ["o que melhora o problema?"],
"HMA_medicamentos_nao_cronicos_tipo" : ["tomou alguma medicação?"],
"HMA_medicamentos_nao_cronicos_dose" : ["qual a dose do medicamento?"],
"HMA_medicamentos_nao_cronicos_posologia" : ["tomou quantas vezes ao dia?"],
"HMA_decalogo_dor_local" : ["onde dói?"],
"HMA_decalogo_dor_irradiacao" : ["a dor se espalha para algum lugar?"],
"HMA_decalogo_dor_qualidade" : ["como é a dor?"],
"HMA_decalogo_dor_intensidade" : ["de 0 a 10, qual o nível da sua dor?"],
"HMA_decalogo_dor_duracao" : ["há quanto tempo dói?"],
"HMA_decalogo_dor_evolucao" : ["com o tempo, a dor piorou, melhorou ou ficou igual?"],
"HMA_decalogo_dor_funcoes_organicas" : ["a dor atrapalhou suas atividades?"],
"HMA_decalogo_dor_fatores_desencadeantes" : ["o que você acha que desencadeou a dor?"],
"HMA_decalogo_dor_fatores_atenuantes" : ["o que melhora a dor?"],
"HMA_decalogo_dor_fatores_agravantes" : ["o que piora a dor?"],
"HMA_decalogo_dor_sintomas_associados" : ["sente mais alguma coisa?"],
"HPP_cirurgias_sim_nao" : ["já fez alguma cirurgia?"],
"HPP_cirurgias_quantidade" : ["quantas cirurgias você fez?"],
"HPP_alergias" : ["tem alguma alergia?"],
"HPP_DCNT" : ["tem alguma doença crônica?"],
"HPP_medicamentos_cronicos_tipo" : ["toma algum remédio todo dia?"],
"HPP_medicamentos_cronicos_dose" : ["qual a dose do medicamento?"],
"HPP_medicamentos_cronicos_posologia" : ["quantas vezes ao dia você toma o medicamento?"],
"HPP_vacinacao" : ["está com a vacinação em dia?"],
"Hfisio_DUM" : ["quando foi a sua última menstruação?"],
"Hfisio_gestacoes_quantidade" : ["quantas vezes você engravidou?"],
"Hfisio_gestacoes_partos" : ["qual o tipo de parto das suas gestações?"],
"Hfisio_gestacoes_abortos" : ["já teve algum aborto?"],
"Hfisio_relacao_sexual_sim_nao" : ["tem relações sexuais?"],
"Hfisio_relacao_sexual_frequencia" : ["com que frequência você tem relações sexuais?"],
"Hfisio_relacao_sexual_parceiros" : ["você tem quantos parceiros sexuais?"],
"Hfisio_relacao_sexual_contraceptivos" : ["usa algum método contraceptivo?"],
"Hfisio_exames_preventivos_mamografia" : ["quando foi sua última mamografia?"],
"Hfisio_exames_preventivos_citopatologico" : ["quando foi seu último papanicolau?"],
"Hfisio_menopausa_inicio" : ["já entrou na menopausa?"],
"Hfisio_menopausa_sintomas" : ["está tendo algum sintoma de menopausa?"],
"Hfisio_puberdade_menarca" : ["quando você menstruou pela primeira vez?"],
"Hfisio_puberdade_telarca" : ["quando seus seios começaram a crescer?"],
"Hfisio_puberdade_pubarca" : ["quando seus pelos pubianos começaram a crescer?"],
"Hfisio_puberdade_sexarca" : ["quando você começou a ter relações sexuais?"],
"Hfamilial_trabalho" : ["alguém do trabalho está doente?"],
"Hfamilial_escola" : ["alguém da sua escola está doente?"],
"HF_DCNT" : ["alguém da sua família tem alguma doença crônica?"],
"HF_obitos" : ["algum familiar próximo já morreu?"],
"Hpsico_renda" : ["qual a sua renda familiar?"],
"Hpsico_habitacao_local" : ["como é sua moradia?"],
"Hpsico_habitacao_saneamento" : ["tem água encanada?"],
"Hpsico_habitacao_condicoes" : ["como é a sua casa?"],
"Hpsico_religiao" : ["tem alguma religião?"],
"Hpsico_escolaridade" : ["estudou até qual série?"],
"Hpsico_relacoes" : ["como são suas relações familiares?"],
"subst_alcool_uso" : ["bebe?"],
"subst_alcool_inicio" : ["quando começou a beber?"],
"subst_alcool_quantidade" : ["quanto você bebe?"],
"subst_tabaco_uso" : ["fuma?"],
"subst_tabaco_inicio" : ["quando começou a fumar?"],
"subst_tabaco_quantidade" : ["quantos cigarros você fuma por dia?"],
"subst_drogas_ilicitas_uso" : ["usa outras drogas?"],
"subst_drogas_ilicitas_inicio" : ["quando começou a usar drogas?"],
"subst_drogas_ilicitas_quantidade" : ["quanto você usa?"],
"habitos_alimentacao" : ["o que você come no dia a dia?"],
"habitos_higiene" : ["quantas vezes você toma banho?"],
"habitos_atividade_fisica" : ["pratica alguma atividade física?"],
"habitos_sono" : ["quantas horas você dorme por noite?"],
"revisao_sistemas_cardiovascular" : ["sente dor no peito?"],
"revisao_sistemas_respiratorio" : ["sente falta de ar?"],
"revisao_sistemas_TGI" : ["tem dor de barriga?"],
"revisao_sistemas_urogenital" : ["tem dor ao urinar?"],
"revisao_sistemas_endocrino" : ["sente muito calor ou muito frio?"],
"revisao_sistemas_neurologico" : ["sente tontura?"],
"revisao_sistemas_osteomuscular" : ["sente dor nas articulações?"],
"revisao_sistemas_hematologico" : ["tem sangramentos?"],
}