RELACAO_IMAGENS_TEXTOS = {
"identificacao_nome" : ["qual o seu nome?"],
"identificacao_idade" : ["qual a sua idade?"],
"identificacao_naturalidade" : ["de onde você é?"],
"identificacao_estado_civil" : ["qual o seu estado civil?"],
"identificacao_profissao" : ["trabalha com o que?"],
"queixa_principal" : ["como posso ajudar?"],
"HMA_inicio" : ["quando começou?"],
"HMA_local" : ["onde está o problema?"],
"HMA_evolucao" : ["ele se manteve igual, melhorou ou piorou?"],
"HMA_irradiacao" : ["ele se espalhou para algum lugar?"],
"HMA_sintomas" : ["sente mais alguma coisa?"],
"HMA_desencadeantes" : ["o que você acha que desencadeou o problema?"],
"HMA_agravantes" : ["o que piora o problema?"],
"HMA_atenuantes" : ["o que melhora o problema?"],
"HMA_medicamentos_nao_cronicos" : ["tomou alguma medicação?"],
"HPP_cirurgias" : ["já fez alguma cirurgia?"],
"HPP_alergias" : ["tem alguma alergia?"],
"HPP_DCNT" : ["tem alguma doença crônica?"],
"HPP_medicamentos_cronicos" : ["toma algum remédio todo dia?"],
"HPP_vacinacao" : ["está com a vacinação em dia?"],
"Hfisio_DUM" : ["quando foi a sua última menstruação?"],
"Hfisio_gestacoes" : ["quantas vezes você engravidou?"],
"Hfisio_partos" : ["quantos filhos você teve?"],
"Hfisio_abortos" : ["já teve algum aborto?"],
"Hfisio_relacao_sexual" : ["tem relações sexuais?"],
"Hfisio_contraceptivos" : ["usa algum método contraceptivo?"],
"Hfisio_mamografia" : ["quando foi sua última mamografia?"],
"Hfisio_citopatologico" : ["quando foi seu último papanicolau?"],
"Hfisio_menarca" : ["quando você menstruou pela primeira vez?"],
"Hfisio_menopausa" : ["já entrou na menopausa?"],
"Hfamilial_local" : ["alguém do trabalho ou da escola teve o mesmo problema?"],
"HF_DCNT" : ["alguém da sua família tem alguma doença crônica?"],
"HF_obitos" : ["algum familiar próximo já morreu?"],
"Hpsico_renda" : ["qual a sua renda familiar?"],
"Hpsico_habitacao" : ["como é sua moradia?"],
"Hpsico_religiao" : ["tem alguma religião?"],
"Hpsico_escolaridade" : ["estudou até qual série?"],
"Hpsico_relacoes" : ["como são suas relações familiares?"],
"subst_alcool" : ["bebe?"],
"subst_tabaco" : ["fuma?"],
"subst_drogas_ilicitas" : ["usa outras drogas?"],
"habitos_alimentacao" : ["o que você come no dia a dia?"],
"habitos_higiene" : ["quantas vezes você toma banho?"],
"habitos_atividade_fisica" : ["pratica alguma atividade física?"],
"habitos_sono" : ["quantas horas você dorme por noite?"],
"revisao_sistemas_cardiovascular" : ["sente dor no peito?"],
"revisao_sistemas_respiratorio" : ["sente falta de ar?"],
"revisao_sistemas_TGI" : ["tem dor de barriga?"],
"revisao_sistemas_genitourinario" : ["tem dor ao urinar?"],
"revisao_sistemas_endocrino" : ["sente muito calor ou muito frio?"],
"revisao_sistemas_neurologico" : ["sente tontura?"],
"revisao_sistemas_osteomuscular" : ["sente dor nas articulações?"],
"revisao_sistemas_hematologico" : ["tem sangramentos?"],
}